"""
Golden master for the traffic simulation.

The one gate on moving the engine into `backend/sim/`. A move is only a move
if the numbers do not change, and "I read the diff carefully" is not proof of
that over 700 lines. So: run a fixed scenario with a fixed seed, dump every
result row the simulation writes into a canonical structure, and compare it
against a file captured before the move.

The fixture is generated by running this module with GOLDEN_REGENERATE=1 and
is committed alongside it. Regenerating it to make a failure go away defeats
the entire point — if this test goes red, either the behaviour changed (find
out why) or the change was deliberate (say so in the commit, then regenerate).

Kept afterwards as a regression net: it is the only test that pins the whole
pipeline end to end rather than one mechanism at a time.
"""

import json
import os
from pathlib import Path

from django.contrib.auth.models import User
from django.test import TestCase
from maps.models import Edge, GameMap, MapVersion, Node, StreetEdge

from game.models import (
    AgentRoute,
    AgentSimulationResult,
    EdgeTrafficSnapshot,
    GameRound,
    GameSession,
    Player,
    PlayerMove,
    RouteSegment,
    SimulationResult,
)
from game.simulation import TrafficSimulator
from game.tests._helpers import muted

GOLDEN_PATH = Path(__file__).parent / "golden" / "sim_golden.json"
GOLDEN_SEED = 20260920

# Floats are rounded before comparison. A pure move reproduces them bit for
# bit, but pinning the last bit of a float buys no detection power and would
# turn a libm difference into a failure that looks like a behaviour change.
PLACES = 6


def _r(value):
    return round(value, PLACES) if isinstance(value, float) else value


class GoldenMasterTests(TestCase):
    """The numbers this scenario produces must not move."""

    def setUp(self):
        self.user = User.objects.create_user(username="golden", password="12345")

    # --- the scenario -------------------------------------------------

    def _street(self, game_map, version, start, end, speed_limit=50, lanes=1):
        edge = Edge.objects.create(
            game_map=game_map, start_node=start, end_node=end, max_lanes=lanes
        )
        edge.map_versions.add(version)
        street = StreetEdge.objects.create(
            edge=edge, speed_limit=speed_limit, lanes=lanes
        )
        street.map_versions.add(version)
        return edge

    def _scenario(self):
        """Two approaches merging onto one lane, plus a bike and a walker.

        Deliberately mixed: the merge exercises queueing, spillback and the
        speed-dependent CO2 curve, while the bike and the walker pin the
        modes that do not queue. A scenario that only jammed cars would let a
        move break everything else silently.
        """
        game_map = GameMap.objects.create(
            name="Golden", x_dim=1000, y_dim=1000, scale=100.0
        )
        version = MapVersion.objects.create(
            game_map=game_map, name="Base", base_version=True
        )
        coords = {
            "north": (0, 20),
            "south": (0, 0),
            "merge": (10, 10),
            "work": (13, 10),
        }
        nodes = {}
        for name, (x, y) in coords.items():
            node = Node.objects.create(game_map=game_map, x_position=x, y_position=y)
            node.map_versions.add(version)
            nodes[name] = node

        shared = self._street(game_map, version, nodes["merge"], nodes["work"])
        north = self._street(game_map, version, nodes["north"], nodes["merge"])
        south = self._street(
            game_map, version, nodes["south"], nodes["merge"], speed_limit=30
        )

        session = GameSession.objects.create(
            game_host=self.user,
            game_name="Golden",
            game_map=game_map,
            max_players=4,
            agent_per_player=1,
            max_rounds=3,
            max_CO2_level=1000000,
            people_per_agent=400,
            departure_std_dev_min=8,
        )
        game_round = GameRound.objects.create(game=session, round_number=1)

        anna = Player.objects.create(name="Anna", game=session)
        ben = Player.objects.create(name="Ben", game=session)
        cleo = Player.objects.create(name="Cleo", game=session)

        self._route(game_round, anna, [north, shared], "car", 1)
        self._route(game_round, ben, [south, shared], "car", 2)
        self._route(game_round, cleo, [north, shared], "bike", 3)
        self._route(game_round, cleo, [south, shared], "walk", 4)
        return game_round

    def _route(self, game_round, player, edges, mode, agent_id):
        move, _ = PlayerMove.objects.get_or_create(
            session_round=game_round, player=player, action="route_submit"
        )
        route = AgentRoute.objects.create(
            player_move=move,
            agent_id=agent_id,
            transport_mode=mode,
            total_distance_m=300.0 * len(edges),
            estimated_time_min=1.0,
        )
        for order, edge in enumerate(edges, start=1):
            RouteSegment.objects.create(
                agent_route=route, edge=edge, order=order, mode=mode
            )
        return route

    # --- the dump -----------------------------------------------------

    def _capture(self):
        game_round = self._scenario()
        simulator = TrafficSimulator(game_round, scale=100.0, seed=GOLDEN_SEED)
        with muted():
            simulator.run_simulation(max_ticks=400)

        result = SimulationResult.objects.get(game_round=game_round)
        agents = AgentSimulationResult.objects.filter(
            simulation=result
        ).select_related("agent_route")
        snaps = EdgeTrafficSnapshot.objects.filter(simulation=result)

        return {
            "total": {
                "status": result.status,
                "total_co2_g": _r(result.total_co2_g),
                "total_cost_eur": _r(result.total_cost_eur),
            },
            "agents": sorted(
                [
                    {
                        "agent_id": a.agent_route.agent_id,
                        "mode": a.agent_route.transport_mode,
                        "mean_trip_time_min": _r(a.mean_trip_time_min),
                        "mean_return_time_min": _r(a.mean_return_time_min),
                        "mean_cost_eur": _r(a.mean_cost_eur),
                        "total_co2_g": _r(a.total_co2_g),
                        "congestion_delay_min": _r(a.congestion_delay_min),
                        "wait_time_min": _r(a.wait_time_min),
                    }
                    for a in agents
                ],
                key=lambda row: (row["agent_id"], row["mode"]),
            ),
            "snapshots": sorted(
                [
                    {
                        "tick": s.time_tick,
                        "vehicle_count": s.vehicle_count,
                        "speed_kmh": _r(s.speed_kmh),
                    }
                    for s in snaps
                ],
                key=lambda row: (row["tick"], row["vehicle_count"], row["speed_kmh"]),
            ),
        }

    # --- the tests ----------------------------------------------------

    def test_the_scenario_matches_the_golden_master(self):
        captured = self._capture()

        if os.environ.get("GOLDEN_REGENERATE"):
            GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
            GOLDEN_PATH.write_text(json.dumps(captured, indent=2) + "\n")
            self.skipTest(f"regenerated {GOLDEN_PATH}")

        self.assertTrue(
            GOLDEN_PATH.exists(),
            f"{GOLDEN_PATH} is missing — regenerate with GOLDEN_REGENERATE=1",
        )
        expected = json.loads(GOLDEN_PATH.read_text())

        self.assertEqual(captured["total"], expected["total"])
        self.assertEqual(captured["agents"], expected["agents"])
        self.assertEqual(captured["snapshots"], expected["snapshots"])

    def test_the_same_seed_reproduces_the_run(self):
        """Without this the golden master proves nothing about the move."""
        first = self._capture()
        second = self._capture()

        self.assertEqual(first, second)

    def test_the_scenario_is_actually_congested(self):
        """A free-flowing golden master would not exercise the queue at all."""
        captured = self._capture()

        cars = [a for a in captured["agents"] if a["mode"] == "car"]
        self.assertTrue(
            any(a["congestion_delay_min"] > 0 for a in cars),
            f"nothing queued: {cars}",
        )
