"""
Golden master for the traffic simulation.

The one gate on moving the engine into `backend/sim/`. A move is only a move
if the numbers do not change, and "I read the diff carefully" is not proof of
that over 700 lines. So: run a fixed scenario with a fixed seed, dump every
result row the simulation writes into a canonical structure, and compare it
against a file captured before the move.

The fixture is generated by running this module with GOLDEN_REGENERATE=1 and
is committed alongside it. Regenerating it to make a failure go away defeats
the entire point — if this test goes red, either the behaviour changed (find
out why) or the change was deliberate (say so in the commit, then regenerate).

Kept afterwards as a regression net: it is the only test that pins the whole
pipeline end to end rather than one mechanism at a time.
"""

import json
import os
import random
import re
from pathlib import Path

from django.contrib.auth.models import User
from django.test import TestCase
from maps.models import (
    BusLine,
    BusLineEdge,
    Edge,
    GameMap,
    MapVersion,
    Node,
    StreetEdge,
    StreetPerRound,
    TrainEdge,
    TrainLine,
    TrainLineEdge,
)

from game.models import (
    AgentRoute,
    AgentSimulationResult,
    EdgeTrafficSnapshot,
    GameRound,
    GameSession,
    Player,
    PlayerMove,
    RouteSegment,
    SimulationResult,
)
from sim import LinkQueueEngine

from game.simulation import TrafficSimulator
from game.tests._helpers import muted

GOLDEN_PATH = Path(__file__).parent / "golden" / "sim_golden.json"
GOLDEN_SEED = 20260920

# Floats are rounded before comparison. A pure move reproduces them bit for
# bit, but pinning the last bit of a float buys no detection power and would
# turn a libm difference into a failure that looks like a behaviour change.
PLACES = 6


def _r(value):
    return round(value, PLACES) if isinstance(value, float) else value


class GoldenMasterTests(TestCase):
    """The numbers this scenario produces must not move."""

    def setUp(self):
        self.user = User.objects.create_user(username="golden", password="12345")

    # --- the scenario -------------------------------------------------

    def _street(self, game_map, version, start, end, speed_limit=50, lanes=1):
        edge = Edge.objects.create(
            game_map=game_map, start_node=start, end_node=end, max_lanes=lanes
        )
        edge.map_versions.add(version)
        street = StreetEdge.objects.create(
            edge=edge, speed_limit=speed_limit, lanes=lanes
        )
        street.map_versions.add(version)
        return edge

    def _scenario(self):
        """Two approaches merging onto one lane, plus a bike and a walker.

        Deliberately mixed: the merge exercises queueing, spillback and the
        speed-dependent CO2 curve, while the bike and the walker pin the
        modes that do not queue. A scenario that only jammed cars would let a
        move break everything else silently.
        """
        game_map = GameMap.objects.create(
            name="Golden", x_dim=1000, y_dim=1000, scale=100.0
        )
        version = MapVersion.objects.create(
            game_map=game_map, name="Base", base_version=True
        )
        coords = {
            "north": (0, 20),
            "south": (0, 0),
            "merge": (10, 10),
            "work": (13, 10),
        }
        nodes = {}
        for name, (x, y) in coords.items():
            node = Node.objects.create(game_map=game_map, x_position=x, y_position=y)
            node.map_versions.add(version)
            nodes[name] = node

        shared = self._street(game_map, version, nodes["merge"], nodes["work"])
        north = self._street(game_map, version, nodes["north"], nodes["merge"])
        south = self._street(
            game_map, version, nodes["south"], nodes["merge"], speed_limit=30
        )

        session = GameSession.objects.create(
            game_host=self.user,
            game_name="Golden",
            game_map=game_map,
            max_players=4,
            agent_per_player=1,
            max_rounds=3,
            max_CO2_level=1000000,
            people_per_agent=400,
            departure_std_dev_min=8,
        )
        game_round = GameRound.objects.create(game=session, round_number=1)

        anna = Player.objects.create(name="Anna", game=session)
        ben = Player.objects.create(name="Ben", game=session)
        cleo = Player.objects.create(name="Cleo", game=session)

        self._route(game_round, anna, [north, shared], "car", 1)
        self._route(game_round, ben, [south, shared], "car", 2)
        self._route(game_round, cleo, [north, shared], "bike", 3)
        self._route(game_round, cleo, [south, shared], "walk", 4)
        return game_round

    def _route(self, game_round, player, edges, mode, agent_id):
        move, _ = PlayerMove.objects.get_or_create(
            session_round=game_round, player=player, action="route_submit"
        )
        route = AgentRoute.objects.create(
            player_move=move,
            agent_id=agent_id,
            transport_mode=mode,
            total_distance_m=300.0 * len(edges),
            estimated_time_min=1.0,
        )
        for order, edge in enumerate(edges, start=1):
            RouteSegment.objects.create(
                agent_route=route, edge=edge, order=order, mode=mode
            )
        return route

    # --- the dump -----------------------------------------------------

    def _capture(self):
        game_round = self._scenario()
        simulator = TrafficSimulator(game_round, scale=100.0, seed=GOLDEN_SEED)
        with muted():
            simulator.run_simulation(max_ticks=400)

        result = SimulationResult.objects.get(game_round=game_round)
        agents = AgentSimulationResult.objects.filter(
            simulation=result
        ).select_related("agent_route")
        snaps = EdgeTrafficSnapshot.objects.filter(simulation=result)

        return {
            "total": {
                "status": result.status,
                "total_co2_g": _r(result.total_co2_g),
                "total_cost_eur": _r(result.total_cost_eur),
            },
            "agents": sorted(
                [
                    {
                        "agent_id": a.agent_route.agent_id,
                        "mode": a.agent_route.transport_mode,
                        "mean_trip_time_min": _r(a.mean_trip_time_min),
                        "mean_return_time_min": _r(a.mean_return_time_min),
                        "mean_cost_eur": _r(a.mean_cost_eur),
                        "total_co2_g": _r(a.total_co2_g),
                        "congestion_delay_min": _r(a.congestion_delay_min),
                        "wait_time_min": _r(a.wait_time_min),
                    }
                    for a in agents
                ],
                key=lambda row: (row["agent_id"], row["mode"]),
            ),
            "snapshots": sorted(
                [
                    {
                        "tick": s.time_tick,
                        "vehicle_count": s.vehicle_count,
                        "speed_kmh": _r(s.speed_kmh),
                    }
                    for s in snaps
                ],
                key=lambda row: (row["tick"], row["vehicle_count"], row["speed_kmh"]),
            ),
        }

    # --- the tests ----------------------------------------------------

    def test_the_scenario_matches_the_golden_master(self):
        captured = self._capture()

        if os.environ.get("GOLDEN_REGENERATE"):
            GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
            GOLDEN_PATH.write_text(json.dumps(captured, indent=2) + "\n")
            self.skipTest(f"regenerated {GOLDEN_PATH}")

        self.assertTrue(
            GOLDEN_PATH.exists(),
            f"{GOLDEN_PATH} is missing — regenerate with GOLDEN_REGENERATE=1",
        )
        expected = json.loads(GOLDEN_PATH.read_text())

        self.assertEqual(captured["total"], expected["total"])
        self.assertEqual(captured["agents"], expected["agents"])
        self.assertEqual(captured["snapshots"], expected["snapshots"])

    def test_the_same_seed_reproduces_the_run(self):
        """Without this the golden master proves nothing about the move."""
        first = self._capture()
        second = self._capture()

        self.assertEqual(first, second)

    def test_the_scenario_is_actually_congested(self):
        """A free-flowing golden master would not exercise the queue at all."""
        captured = self._capture()

        cars = [a for a in captured["agents"] if a["mode"] == "car"]
        self.assertTrue(
            any(a["congestion_delay_min"] > 0 for a in cars),
            f"nothing queued: {cars}",
        )


GOLDEN_PT_PATH = Path(__file__).parent / "golden" / "sim_golden_pt.json"
GOLDEN_PT_SEED = 20261002


class PublicTransportGoldenMasterTests(TestCase):
    """The same net over public transport, both ways, before the engine moves.

    The first golden master's scenario is car / car / bike / walk, so no
    change to a timetable, to boarding or to the way home could ever turn it
    red. This one rides a bus in mixed traffic and on a bus lane, two trains,
    a transfer from one to the other, and a way home on lines of its own —
    with seats few enough that people are refused at a stop and the timetable
    runs past its base.

    It pins more than the first: the network's own CO2 and cost, what people
    paid, the street speeds the next round routes on, the replay the screen
    draws and the log the host downloads. All of them move with the engine.
    Every id in the dump is a name, because primary keys climb through the
    suite and a run alone would not match a run in the whole of it.
    """

    def setUp(self):
        self.user = User.objects.create_user(username="golden-pt", password="12345")

    # --- the scenario -------------------------------------------------

    def _node(self, name, x):
        node = Node.objects.create(
            game_map=self.game_map, name=name, x_position=x, y_position=0
        )
        node.map_versions.add(self.version)
        self.names[("node", node.pk)] = name
        return node

    def _street(self, start, end, lanes=1, speed_limit=50, bus_lane=False):
        edge = Edge.objects.create(
            game_map=self.game_map, start_node=start, end_node=end, max_lanes=lanes
        )
        edge.map_versions.add(self.version)
        StreetEdge.objects.create(
            edge=edge,
            speed_limit=speed_limit,
            lanes=lanes,
            dedicated_bus_lane=bus_lane,
        ).map_versions.add(self.version)
        self.names[("edge", edge.pk)] = f"{start.name}>{end.name}"
        return edge

    def _rail(self, start, end):
        edge = Edge.objects.create(
            game_map=self.game_map, start_node=start, end_node=end
        )
        edge.map_versions.add(self.version)
        TrainEdge.objects.create(edge=edge).map_versions.add(self.version)
        self.names[("edge", edge.pk)] = f"{start.name}={end.name}"
        return edge

    def _bus(self, name, edges, capacity):
        line = BusLine.objects.create(
            game_map=self.game_map, name=name, intervall=10, bus_capacity=capacity
        )
        line.map_versions.add(self.version)
        for order, edge in enumerate(edges):
            BusLineEdge.objects.create(
                bus_line=line, street_edge=edge.streetedge_set.first(), order=order
            ).map_versions.add(self.version)
        return line

    def _train(self, name, edges, capacity):
        line = TrainLine.objects.create(
            game_map=self.game_map, name=name, intervall=15, train_capacity=capacity
        )
        line.map_versions.add(self.version)
        for order, edge in enumerate(edges):
            TrainLineEdge.objects.create(
                train_line=line, train_edge=edge.trainedge_set.first(), order=order
            ).map_versions.add(self.version)
        return line

    def _scenario(self):
        """A corridor west to east, five stops, streets both ways and rail.

        Cars share one lane with the bus everywhere but b–c, where the bus
        has a lane of its own. M1 runs east and M2 west on the streets; S1
        east and S2 west on the rail, which stops only at b. Rosa changes
        from the bus to the train at b, both ways.
        """
        self.names = {}
        self.game_map = GameMap.objects.create(
            name="Golden PT", x_dim=1000, y_dim=1000, scale=100.0
        )
        self.version = MapVersion.objects.create(
            game_map=self.game_map, name="Base", base_version=True
        )
        w, a, b, c, e = (
            self._node(name, x)
            for name, x in (("w", 0), ("a", 6), ("b", 12), ("c", 18), ("e", 24))
        )

        east = [
            self._street(w, a),
            self._street(a, b, lanes=2),
            self._street(b, c, lanes=2, bus_lane=True),
            self._street(c, e, speed_limit=30),
        ]
        west = [
            self._street(e, c, speed_limit=30),
            self._street(c, b, lanes=2, bus_lane=True),
            self._street(b, a, lanes=2),
            self._street(a, w),
        ]
        rail_east = [self._rail(w, b), self._rail(b, e)]
        rail_west = [self._rail(e, b), self._rail(b, w)]

        m1 = self._bus("M1", east, capacity=40)
        m2 = self._bus("M2", west, capacity=40)
        s1 = self._train("S1", rail_east, capacity=200)
        s2 = self._train("S2", rail_west, capacity=200)

        session = GameSession.objects.create(
            game_host=self.user,
            game_name="Golden PT",
            game_map=self.game_map,
            active_map_version=self.version,
            max_players=5,
            agent_per_player=1,
            max_rounds=3,
            max_CO2_level=1000000,
            people_per_agent=150,
            departure_std_dev_min=10,
        )
        game_round = GameRound.objects.create(game=session, round_number=1)
        players = {
            name: Player.objects.create(name=name, game=session)
            for name in ("Anna", "Ben", "Cleo", "Dara", "Emil")
        }

        def legs(player, agent_id, mode, parts, direction):
            self._route(game_round, players[player], agent_id, mode, parts, direction)

        for direction, streets, bus, rails, train in (
            ("out", east, m1, rail_east, s1),
            ("home", west, m2, rail_west, s2),
        ):
            legs("Anna", 1, "car", [("car", streets, None)], direction)
            legs("Ben", 2, "public", [("bus", streets, bus)], direction)
            legs("Dara", 4, "public", [("train", rails, train)], direction)
            legs("Emil", 5, "bike", [("bike", streets, None)], direction)
        legs(
            "Cleo",
            3,
            "public",
            [("bus", east[:2], m1), ("train", rail_east[1:], s1)],
            "out",
        )
        legs(
            "Cleo",
            3,
            "public",
            [("train", rail_west[:1], s2), ("bus", west[2:], m2)],
            "home",
        )
        return game_round

    def _route(self, game_round, player, agent_id, mode, parts, direction):
        move, _ = PlayerMove.objects.get_or_create(
            session_round=game_round, player=player, action="route_submit"
        )
        route = AgentRoute.objects.create(
            player_move=move,
            agent_id=agent_id,
            direction=direction,
            transport_mode=mode,
            total_distance_m=600.0 * sum(len(edges) for _, edges, _ in parts),
            estimated_time_min=4.0,
        )
        order = 1
        for segment_mode, edges, line in parts:
            for edge in edges:
                RouteSegment.objects.create(
                    agent_route=route,
                    order=order,
                    edge=edge,
                    mode=segment_mode,
                    pt_line_id=line.pk if line else None,
                )
                order += 1
        self.names[("route", route.pk)] = f"{player.name}/{direction}"
        return route

    # --- the dump -----------------------------------------------------

    def _name(self, kind, pk):
        return self.names.get((kind, pk), f"{kind}?")

    def _replay(self, replay):
        """The replay with every primary key turned into a name."""
        dots = []
        for dot in replay["dots"]:
            legs = []
            for kind, ref, start, end, from_node in dot["legs"]:
                if kind == "e":
                    ref = self._name("edge", ref)
                elif kind == "s":
                    ref = self._name("node", ref)
                if from_node is not None:
                    from_node = self._name("node", from_node)
                legs.append([kind, ref, start, end, from_node])
            dots.append(
                {
                    **dot,
                    "route": (
                        self._name("route", dot["route"])
                        if dot["route"] is not None
                        else None
                    ),
                    "legs": legs,
                }
            )
        return {**replay, "dots": dots}

    def _log(self, text):
        """The host's log with every primary key turned into a name."""
        nodes = {pk: name for (kind, pk), name in self.names.items() if kind == "node"}
        text = re.sub(r"Edge \d+ \(", "Edge (", text)
        text = re.sub(
            r"(rides \S+ )(\d+)→(\d+)",
            lambda m: (
                f"{m.group(1)}{nodes.get(int(m.group(2)), '?')}"
                f"→{nodes.get(int(m.group(3)), '?')}"
            ),
            text,
        )
        return text.splitlines()

    def _capture(self):
        game_round = self._scenario()
        simulator = TrafficSimulator(game_round, scale=100.0, seed=GOLDEN_PT_SEED)
        with muted():
            simulator.run_simulation()

        result = SimulationResult.objects.get(game_round=game_round)
        agents = AgentSimulationResult.objects.filter(
            simulation=result
        ).select_related("agent_route")
        snaps = EdgeTrafficSnapshot.objects.filter(simulation=result)
        speeds = StreetPerRound.objects.filter(game_round=game_round).select_related(
            "edge"
        )

        return {
            "total": {
                "status": result.status,
                "total_co2_g": _r(result.total_co2_g),
                "total_cost_eur": _r(result.total_cost_eur),
                "network_co2_g": _r(result.network_co2_g),
                "network_cost_eur": _r(result.network_cost_eur),
            },
            "agents": sorted(
                [
                    {
                        "route": self._name("route", a.agent_route_id),
                        "mode": a.agent_route.transport_mode,
                        "mean_trip_time_min": _r(a.mean_trip_time_min),
                        "mean_return_time_min": _r(a.mean_return_time_min),
                        "mean_cost_eur": _r(a.mean_cost_eur),
                        "mean_paid_eur": _r(a.mean_paid_eur),
                        "total_co2_g": _r(a.total_co2_g),
                        "congestion_delay_min": _r(a.congestion_delay_min),
                        "wait_time_min": _r(a.wait_time_min),
                    }
                    for a in agents
                ],
                key=lambda row: row["route"],
            ),
            "snapshots": sorted(
                [
                    {
                        "edge": self._name("edge", s.edge_id),
                        "tick": s.time_tick,
                        "vehicle_count": s.vehicle_count,
                        "waiting_count": s.waiting_count,
                        "speed_kmh": _r(s.speed_kmh),
                    }
                    for s in snaps
                ],
                key=lambda row: (row["edge"], row["tick"]),
            ),
            "street_speeds": sorted(
                [
                    [self._name("edge", s.edge.edge_id), s.speed_under_load]
                    for s in speeds
                ]
            ),
            "replay": self._replay(result.replay),
            "log": self._log(result.detailed_log),
        }

    # --- the tests ----------------------------------------------------

    def test_the_scenario_matches_the_golden_master(self):
        captured = self._capture()

        if os.environ.get("GOLDEN_REGENERATE"):
            GOLDEN_PT_PATH.parent.mkdir(parents=True, exist_ok=True)
            GOLDEN_PT_PATH.write_text(
                json.dumps(captured, indent=1, ensure_ascii=False) + "\n"
            )
            self.skipTest(f"regenerated {GOLDEN_PT_PATH}")

        self.assertTrue(
            GOLDEN_PT_PATH.exists(),
            f"{GOLDEN_PT_PATH} is missing — regenerate with GOLDEN_REGENERATE=1",
        )
        expected = json.loads(GOLDEN_PT_PATH.read_text())

        for key in ("total", "agents", "snapshots", "street_speeds", "replay", "log"):
            with self.subTest(key=key):
                self.assertEqual(captured[key], expected[key])

    def test_the_same_seed_reproduces_the_run(self):
        """Without this the golden master proves nothing about the move."""
        self.assertEqual(self._capture(), self._capture())

    def test_the_scenario_exercises_what_it_claims_to(self):
        """A golden master over a quiet timetable would pin nothing.

        Riders refused for want of a seat, runs past the base timetable, a
        transfer on both ways, the way home in the replay, and a queue the
        cars share with the bus.
        """
        captured = self._capture()
        log = "\n".join(captured["log"])

        self.assertRegex(log, r"[1-9]\d* refusals at the stop")
        self.assertRegex(log, r"timetabled \+ \d+ extra")
        self.assertIn("rides M1 w→b, rides S1 b→e", log)
        self.assertIn("rides S2 e→b, rides M2 b→w", log)
        self.assertEqual(
            {dot["pass"] for dot in captured["replay"]["dots"]}, {"out", "home"}
        )
        self.assertTrue(
            any(a["congestion_delay_min"] > 0 for a in captured["agents"]),
            captured["agents"],
        )
        self.assertTrue(all(a["mean_return_time_min"] > 0 for a in captured["agents"]))
        self.assertEqual(captured["replay"]["endings"], {"unfinished": 0, "stranded": 0})

    def test_the_engine_alone_reproduces_the_round(self):
        """The seam is real: the scenario the adapter read is all the engine needs.

        The same round, run again by `LinkQueueEngine` from nothing but the two
        scenarios the game read it into and the same seed — no rows, no adapter
        — comes out the same, route by route, sample by sample, dot by dot.
        """
        simulator = TrafficSimulator(
            self._scenario(), scale=100.0, seed=GOLDEN_PT_SEED
        )
        with muted():
            simulator.run_simulation()
            home = simulator.home_pass.scenario
            engine = LinkQueueEngine(simulator.scenario, random.Random(GOLDEN_PT_SEED))
            engine.run_round(way_home=lambda rng: LinkQueueEngine(home, rng))

        self.assertEqual(engine.outcomes, simulator.outcomes)
        self.assertEqual(engine.home_pass.outcomes, simulator.home_pass.outcomes)
        self.assertEqual(
            engine.link_samples + engine.home_pass.link_samples,
            simulator.link_samples + simulator.home_pass.link_samples,
        )
        self.assertEqual(engine.observed_speeds(), simulator.observed_speeds())
        self.assertEqual(engine.build_replay(), simulator.build_replay())
        self.assertEqual(engine.sim_log.get_text(), simulator.sim_log.get_text())
