# Generated by Django 5.2.8 on 2026-02-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveSmallIntegerField()),
                ('transport_mode', models.CharField(choices=[('car', 'Car'), ('public', 'Public Transport'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=20)),
                ('optimization', models.CharField(blank=True, choices=[('time', 'Fastest'), ('distance', 'Shortest'), ('co2', 'Lowest CO2')], max_length=20, null=True)),
                ('total_distance_m', models.FloatField()),
                ('estimated_time_min', models.FloatField()),
            ],
            options={
                'ordering': ('player_move', 'agent_id'),
            },
        ),
        migrations.CreateModel(
            name='BikeMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions_g_per_km', models.FloatField(default=18.0)),
                ('cost_per_km', models.FloatField(default=0.08)),
            ],
        ),
        migrations.CreateModel(
            name='BusMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=1200.0)),
                ('base_cost_per_km', models.FloatField(default=4.5)),
            ],
        ),
        migrations.CreateModel(
            name='CarMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=166.8)),
                ('base_cost_per_km', models.FloatField(default=0.32)),
            ],
        ),
        migrations.CreateModel(
            name='EdgeTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_tick', models.PositiveSmallIntegerField()),
                ('vehicle_count', models.PositiveIntegerField()),
                ('speed_kmh', models.FloatField()),
            ],
            options={
                'ordering': ('simulation', 'time_tick', 'edge'),
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_emissions_g', models.FloatField(default=0.0)),
                ('total_cost_eur', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('game', 'round_number'),
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_id', models.CharField(max_length=6, unique=True)),
                ('game_password', models.CharField(blank=True, max_length=50, null=True)),
                ('game_qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('map_updates', models.BooleanField(default=False)),
                ('max_players', models.PositiveIntegerField()),
                ('agent_per_player', models.PositiveIntegerField()),
                ('max_rounds', models.PositiveIntegerField()),
                ('max_CO2_level', models.PositiveIntegerField()),
                ('chat_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('people_per_agent', models.PositiveIntegerField(default=1000)),
                ('tick_duration_min', models.PositiveSmallIntegerField(default=5)),
                ('morning_departure_hour', models.PositiveSmallIntegerField(default=9)),
                ('evening_departure_hour', models.PositiveSmallIntegerField(default=17)),
                ('departure_std_dev_min', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_id', models.CharField(blank=True, editable=False, max_length=6, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('controlled_by_host', models.BooleanField(default=False)),
                ('agent_assignments', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('game', 'name', 'joined_at'),
            },
        ),
        migrations.CreateModel(
            name='PlayerMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('session_round', 'moved_at'),
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=20)),
                ('pt_line_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('agent_route', 'order'),
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_co2_g', models.FloatField(default=0.0)),
                ('total_cost_eur', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=3500.0)),
                ('base_cost_per_km', models.FloatField(default=12.0)),
            ],
        ),
        migrations.CreateModel(
            name='WalkingMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_trip_time_min', models.FloatField()),
                ('mean_return_time_min', models.FloatField(default=0.0)),
                ('mean_cost_eur', models.FloatField()),
                ('total_co2_g', models.FloatField()),
                ('congestion_delay_min', models.FloatField(default=0.0)),
                ('wait_time_min', models.FloatField(default=0.0)),
                ('agent_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='game.agentroute')),
            ],
        ),
    ]
