# Generated by Django 5.2.8 on 2026-02-06 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_emissions_g', models.FloatField(default=0.0)),
                ('total_cost_eur', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('game', 'round_number'),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_id', models.CharField(blank=True, editable=False, max_length=6, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('controlled_by_host', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('game', 'name', 'joined_at'),
            },
        ),
        migrations.CreateModel(
            name='PlayerMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('session_round', 'moved_at'),
            },
        ),
        migrations.CreateModel(
            name='TrainMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=3500.0)),
                ('base_cost_per_km', models.FloatField(default=12.0)),
            ],
        ),
        migrations.CreateModel(
            name='WalkingMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=166.8)),
                ('base_cost_per_km', models.FloatField(default=0.32)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='BusMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=1200.0)),
                ('base_cost_per_km', models.FloatField(default=4.5)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='BikeMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions_g_per_km', models.FloatField(default=18.0)),
                ('cost_per_km', models.FloatField(default=0.08)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_id', models.CharField(max_length=6, unique=True)),
                ('game_password', models.CharField(blank=True, max_length=50, null=True)),
                ('game_qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('map_updates', models.BooleanField(default=False)),
                ('max_players', models.PositiveIntegerField()),
                ('agent_per_player', models.PositiveIntegerField()),
                ('max_rounds', models.PositiveIntegerField()),
                ('max_CO2_level', models.PositiveIntegerField()),
                ('chat_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('game_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
