# Generated by Django 5.2.8 on 2026-02-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edgetrafficsnapshot',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge'),
        ),
        migrations.AddField(
            model_name='carmobility',
            name='session_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround'),
        ),
        migrations.AddField(
            model_name='busmobility',
            name='session_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround'),
        ),
        migrations.AddField(
            model_name='bikemobility',
            name='session_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.gamemap'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playermove',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.player'),
        ),
        migrations.AddField(
            model_name='playermove',
            name='session_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.gameround'),
        ),
        migrations.AddField(
            model_name='agentroute',
            name='player_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='game.playermove'),
        ),
        migrations.AddField(
            model_name='routesegment',
            name='agent_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='game.agentroute'),
        ),
        migrations.AddField(
            model_name='routesegment',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='game_round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='game.gameround'),
        ),
        migrations.AddField(
            model_name='edgetrafficsnapshot',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_snapshots', to='game.simulationresult'),
        ),
        migrations.AddField(
            model_name='agentsimulationresult',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_results', to='game.simulationresult'),
        ),
        migrations.AddField(
            model_name='trainmobility',
            name='session_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround'),
        ),
        migrations.AddField(
            model_name='walkingmobility',
            name='session_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround'),
        ),
        migrations.AlterUniqueTogether(
            name='gameround',
            unique_together={('game', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='playermove',
            unique_together={('session_round', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='agentroute',
            unique_together={('player_move', 'agent_id')},
        ),
        migrations.AlterUniqueTogether(
            name='routesegment',
            unique_together={('agent_route', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='edgetrafficsnapshot',
            unique_together={('simulation', 'edge', 'time_tick')},
        ),
        migrations.AlterUniqueTogether(
            name='agentsimulationresult',
            unique_together={('simulation', 'agent_route')},
        ),
    ]
