# Generated by Django 5.2.8 on 2026-01-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='total_cost_eur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='total_emissions_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='GameStats',
        ),
    ]
