# Generated by Django 5.2.8 on 2026-02-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='detailed_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
