# Generated by Django 5.2.8 on 2025-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
