# Generated by Django 5.2.8 on 2026-02-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameround_total_cost_eur_gameround_total_emissions_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agent_assignments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
