# Generated by Django 5.2.8 on 2026-01-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamesession_lobby_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='lobby_open',
            field=models.BooleanField(default=True),
        ),
    ]
