# Generated by Django 5.2.8 on 2025-12-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_chat_enabled_player_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='controlled_by_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr_codes/'),
        ),
    ]
