# Generated by Django 5.2.8 on 2026-02-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_add_detailed_log_to_simulationresult'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='between_round_phase',
            field=models.CharField(choices=[('none', 'None'), ('stats', 'Stats Review'), ('discussion', 'Discussion'), ('voting', 'Voting')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='active_map_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_sessions', to='maps.mapversion'),
        ),
        migrations.CreateModel(
            name='MapVersionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_votes', to='game.gameround')),
                ('map_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.mapversion')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_votes', to='game.player')),
            ],
            options={
                'ordering': ('game_round', 'voted_at'),
                'unique_together': {('game_round', 'player')},
            },
        ),
    ]
