# Generated by Django 5.2.8 on 2026-02-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_agent_assignments_to_player'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveSmallIntegerField()),
                ('transport_mode', models.CharField(choices=[('car', 'Car'), ('public', 'Public Transport'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=20)),
                ('optimization', models.CharField(blank=True, choices=[('time', 'Fastest'), ('distance', 'Shortest'), ('co2', 'Lowest CO2')], max_length=20, null=True)),
                ('total_distance_m', models.FloatField()),
                ('estimated_time_min', models.FloatField()),
                ('player_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='game.playermove')),
            ],
            options={
                'ordering': ('player_move', 'agent_id'),
                'unique_together': {('player_move', 'agent_id')},
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_co2_g', models.FloatField(default=0.0)),
                ('total_cost_eur', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('game_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=20)),
                ('pt_line_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='game.agentroute')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge')),
            ],
            options={
                'ordering': ('agent_route', 'order'),
                'unique_together': {('agent_route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='EdgeTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_tick', models.PositiveSmallIntegerField()),
                ('vehicle_count', models.PositiveIntegerField()),
                ('speed_kmh', models.FloatField()),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_snapshots', to='game.simulationresult')),
            ],
            options={
                'ordering': ('simulation', 'time_tick', 'edge'),
                'unique_together': {('simulation', 'edge', 'time_tick')},
            },
        ),
        migrations.CreateModel(
            name='AgentSimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_trip_time_min', models.FloatField()),
                ('mean_return_time_min', models.FloatField(default=0.0)),
                ('mean_cost_eur', models.FloatField()),
                ('total_co2_g', models.FloatField()),
                ('congestion_delay_min', models.FloatField(default=0.0)),
                ('wait_time_min', models.FloatField(default=0.0)),
                ('agent_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='game.agentroute')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_results', to='game.simulationresult')),
            ],
            options={
                'unique_together': {('simulation', 'agent_route')},
            },
        ),
    ]
