# Generated by Django 5.2.8 on 2026-01-25 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gamesession_lobby_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermove',
            options={'ordering': ('session_round', 'moved_at')},
        ),
        migrations.RenameField(
            model_name='playermove',
            old_name='game_round',
            new_name='session_round',
        ),
        migrations.AlterUniqueTogether(
            name='playermove',
            unique_together={('session_round', 'player')},
        ),
        migrations.AddField(
            model_name='playermove',
            name='moved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BikeMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions_g_per_km', models.FloatField(default=18.0)),
                ('cost_per_km', models.FloatField(default=0.08)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='BusMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=1200.0)),
                ('base_cost_per_km', models.FloatField(default=4.5)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='CarMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=166.8)),
                ('base_cost_per_km', models.FloatField(default=0.32)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_emissions_g', models.FloatField(default=0.0)),
                ('total_cost_eur', models.FloatField(default=0.0)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='TrainMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_emissions_g_per_km', models.FloatField(default=3500.0)),
                ('base_cost_per_km', models.FloatField(default=12.0)),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='WalkingMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.RemoveField(
            model_name='playermove',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='playermove',
            name='updated_at',
        ),
    ]
