# Generated by Django 5.2.8 on 2026-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_stalemate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
