# Generated by Django 5.2.8 on 2026-09-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamesession_anonymised_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='vote_option_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StatsAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acked_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_acks', to='game.gameround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_acks', to='game.player')),
            ],
            options={
                'ordering': ('game_round', 'acked_at'),
                'unique_together': {('game_round', 'player')},
            },
        ),
    ]
