# Generated by Django 5.2.8 on 2026-09-17 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_id_unique_per_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='idle_end_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
