# Generated by Django 5.2.8 on 2026-09-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gamesession_idle_end_days_gamesession_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('co2_limit', 'CO2 budget spent'), ('max_rounds', 'All rounds played'), ('host', 'Ended by the host'), ('idle', 'Idle for too long')], help_text="Why the game ended. Written once, when it ends — it cannot be worked out afterwards, which is why every ending that was not the CO2 budget used to report 'all rounds played'.", max_length=20, null=True),
        ),
    ]
