# Generated by Django 5.2.8 on 2026-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamesession_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgetrafficsnapshot',
            name='waiting_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
