# Generated by Django 5.2.8 on 2026-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gameround_vote_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsimulationresult',
            name='mean_paid_eur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='network_co2_g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='network_cost_eur',
            field=models.FloatField(default=0.0),
        ),
    ]
