# Generated by Django 5.2.8 on 2026-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_agentsimulationresult_mean_paid_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='replay',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
