# Generated by Django 5.2.8 on 2026-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_simulationresult_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='people_per_agent',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='trainmobility',
            name='base_emissions_g_per_km',
            field=models.FloatField(default=1500.0),
        ),
    ]
