# Generated by Django 5.2.8 on 2026-10-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_co2_kalibrierung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentroute',
            options={'ordering': ('player_move', 'agent_id', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='agentroute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agentroute',
            name='direction',
            field=models.CharField(choices=[('out', 'Hinweg'), ('home', 'Rückweg')], default='out', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='agentroute',
            unique_together={('player_move', 'agent_id', 'direction')},
        ),
    ]
