# Generated by Django 5.2.8 on 2026-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_rueckweg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemobility',
            name='cost_per_km',
            field=models.FloatField(default=0.03),
        ),
    ]
