# Generated by Django 5.2.8 on 2026-10-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_fahrrad_unterhalt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busmobility',
            name='session_round',
        ),
        migrations.RemoveField(
            model_name='carmobility',
            name='session_round',
        ),
        migrations.RemoveField(
            model_name='trainmobility',
            name='session_round',
        ),
        migrations.RemoveField(
            model_name='walkingmobility',
            name='session_round',
        ),
        migrations.DeleteModel(
            name='BikeMobility',
        ),
        migrations.DeleteModel(
            name='BusMobility',
        ),
        migrations.DeleteModel(
            name='CarMobility',
        ),
        migrations.DeleteModel(
            name='TrainMobility',
        ),
        migrations.DeleteModel(
            name='WalkingMobility',
        ),
    ]
