# Generated by Django 5.2.8 on 2026-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_mobility_weg'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='co2_kg_per_person',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='people_per_agent',
            field=models.PositiveIntegerField(default=106),
        ),
    ]
