# Generated by Django 5.2 on 2025-10-28 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='open', max_length=10)),
                ('max_rounds', models.PositiveSmallIntegerField(default=10)),
                ('wins_to_win', models.PositiveSmallIntegerField(default=5)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('result', models.CharField(blank=True, choices=[('heads', 'Heads'), ('tails', 'Tails')], max_length=5, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('choice', models.CharField(choices=[('heads', 'Heads'), ('tails', 'Tails')], max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.round')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'round'), name='unique_player_move_per_round')],
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('session', 'round_number'), name='unique_round_number_per_session'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unique_player_per_session'),
        ),
    ]
