# Generated by Django 5.2 on 2025-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='New Session', max_length=150),
        ),
    ]
