# Generated by Django 5.2 on 2025-10-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermove',
            old_name='choice',
            new_name='move_choice',
        ),
    ]
