# Generated by Django 5.2.8 on 2025-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_session_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_status',
            field=models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('terminated', 'Terminated')], default='open', max_length=10),
        ),
    ]
