# Generated by Django 5.2.8 on 2025-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_session_qr_code_alter_session_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
