/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as MapsMapIdRouteImport } from './routes/maps/$mapId'
import { Route as GameGameIdRouteImport } from './routes/game/$gameId'
import { Route as MapsMapIdIndexRouteImport } from './routes/maps/$mapId.index'
import { Route as MapsMapIdEditorRouteImport } from './routes/maps/$mapId.editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/maps/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdIndexRoute = MapsMapIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapsMapIdRoute,
} as any)
const MapsMapIdEditorRoute = MapsMapIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => MapsMapIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/maps/$mapId': typeof MapsMapIdRouteWithChildren
  '/game/': typeof GameIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/maps/$mapId/editor': typeof MapsMapIdEditorRoute
  '/maps/$mapId/': typeof MapsMapIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game': typeof GameIndexRoute
  '/maps': typeof MapsIndexRoute
  '/maps/$mapId/editor': typeof MapsMapIdEditorRoute
  '/maps/$mapId': typeof MapsMapIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/maps/$mapId': typeof MapsMapIdRouteWithChildren
  '/game/': typeof GameIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/maps/$mapId/editor': typeof MapsMapIdEditorRoute
  '/maps/$mapId/': typeof MapsMapIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game/$gameId'
    | '/maps/$mapId'
    | '/game/'
    | '/maps/'
    | '/maps/$mapId/editor'
    | '/maps/$mapId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game/$gameId'
    | '/game'
    | '/maps'
    | '/maps/$mapId/editor'
    | '/maps/$mapId'
  id:
    | '__root__'
    | '/'
    | '/game/$gameId'
    | '/maps/$mapId'
    | '/game/'
    | '/maps/'
    | '/maps/$mapId/editor'
    | '/maps/$mapId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGameIdRoute: typeof GameGameIdRoute
  MapsMapIdRoute: typeof MapsMapIdRouteWithChildren
  GameIndexRoute: typeof GameIndexRoute
  MapsIndexRoute: typeof MapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId': {
      id: '/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId/': {
      id: '/maps/$mapId/'
      path: '/'
      fullPath: '/maps/$mapId/'
      preLoaderRoute: typeof MapsMapIdIndexRouteImport
      parentRoute: typeof MapsMapIdRoute
    }
    '/maps/$mapId/editor': {
      id: '/maps/$mapId/editor'
      path: '/editor'
      fullPath: '/maps/$mapId/editor'
      preLoaderRoute: typeof MapsMapIdEditorRouteImport
      parentRoute: typeof MapsMapIdRoute
    }
  }
}

interface MapsMapIdRouteChildren {
  MapsMapIdEditorRoute: typeof MapsMapIdEditorRoute
  MapsMapIdIndexRoute: typeof MapsMapIdIndexRoute
}

const MapsMapIdRouteChildren: MapsMapIdRouteChildren = {
  MapsMapIdEditorRoute: MapsMapIdEditorRoute,
  MapsMapIdIndexRoute: MapsMapIdIndexRoute,
}

const MapsMapIdRouteWithChildren = MapsMapIdRoute._addFileChildren(
  MapsMapIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGameIdRoute: GameGameIdRoute,
  MapsMapIdRoute: MapsMapIdRouteWithChildren,
  GameIndexRoute: GameIndexRoute,
  MapsIndexRoute: MapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
