/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as LobbyIndexRouteImport } from './routes/lobby/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as MapsMapIdRouteImport } from './routes/maps/$mapId'
import { Route as LobbyGameIdRouteImport } from './routes/lobby/$gameId'
import { Route as GameGameIdRouteImport } from './routes/game/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyIndexRoute = LobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/maps/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyGameIdRoute = LobbyGameIdRouteImport.update({
  id: '/lobby/$gameId',
  path: '/lobby/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/game': typeof GameIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/maps': typeof MapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/game': typeof GameIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/maps': typeof MapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/game/': typeof GameIndexRoute
  '/lobby/': typeof LobbyIndexRoute
  '/maps/': typeof MapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game/$gameId'
    | '/lobby/$gameId'
    | '/maps/$mapId'
    | '/game'
    | '/lobby'
    | '/maps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game/$gameId'
    | '/lobby/$gameId'
    | '/maps/$mapId'
    | '/game'
    | '/lobby'
    | '/maps'
  id:
    | '__root__'
    | '/'
    | '/game/$gameId'
    | '/lobby/$gameId'
    | '/maps/$mapId'
    | '/game/'
    | '/lobby/'
    | '/maps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGameIdRoute: typeof GameGameIdRoute
  LobbyGameIdRoute: typeof LobbyGameIdRoute
  MapsMapIdRoute: typeof MapsMapIdRoute
  GameIndexRoute: typeof GameIndexRoute
  LobbyIndexRoute: typeof LobbyIndexRoute
  MapsIndexRoute: typeof MapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/': {
      id: '/lobby/'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId': {
      id: '/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$gameId': {
      id: '/lobby/$gameId'
      path: '/lobby/$gameId'
      fullPath: '/lobby/$gameId'
      preLoaderRoute: typeof LobbyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGameIdRoute: GameGameIdRoute,
  LobbyGameIdRoute: LobbyGameIdRoute,
  MapsMapIdRoute: MapsMapIdRoute,
  GameIndexRoute: GameIndexRoute,
  LobbyIndexRoute: LobbyIndexRoute,
  MapsIndexRoute: MapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
