# Generated by Django 5.2.8 on 2026-02-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('name', 'short'),
            },
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_dim', models.PositiveSmallIntegerField(default=10)),
                ('y_dim', models.PositiveSmallIntegerField(default=10)),
                ('scale', models.FloatField(default=1.0)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='map_backgrounds/')),
                ('image_offset_x', models.FloatField(default=0.0)),
                ('image_offset_y', models.FloatField(default=0.0)),
                ('image_scale', models.FloatField(default=1.0)),
                ('image_crop_top', models.FloatField(default=0.0)),
                ('image_crop_right', models.FloatField(default=0.0)),
                ('image_crop_bottom', models.FloatField(default=0.0)),
                ('image_crop_left', models.FloatField(default=0.0)),
                ('max_player', models.PositiveSmallIntegerField(default=4)),
                ('walk_speed_kmh', models.PositiveSmallIntegerField(default=5)),
                ('bike_speed_kmh', models.PositiveSmallIntegerField(default=20)),
                ('default_car_speed_kmh', models.PositiveSmallIntegerField(default=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='MapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_version', models.BooleanField(default=False)),
                ('poll_text', models.TextField(default='Die Karte soll ... ')),
                ('revert_poll_text', models.TextField(default='Die Karte soll ... ')),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='maps.mapversion')),
            ],
            options={
                'ordering': ('game_map', '-base_version', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('intervall', models.PositiveSmallIntegerField(default=5)),
                ('bus_capacity', models.PositiveSmallIntegerField()),
                ('bus_speed_kmh', models.PositiveSmallIntegerField(default=30)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('map_versions', models.ManyToManyField(to='maps.mapversion')),
            ],
            options={
                'ordering': ('game_map', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('map_versions', models.ManyToManyField(to='maps.mapversion')),
                ('node_type', models.ManyToManyField(to='maps.nodetype')),
            ],
            options={
                'ordering': ('game_map', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('biking', models.BooleanField(default=True)),
                ('walking', models.BooleanField(default=True)),
                ('max_lanes', models.PositiveSmallIntegerField(default=1)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('map_versions', models.ManyToManyField(to='maps.mapversion')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='maps.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='maps.node')),
            ],
            options={
                'ordering': ('game_map', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='StreetEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limit', models.PositiveSmallIntegerField(default=50)),
                ('lanes', models.PositiveSmallIntegerField(default=1)),
                ('dedicated_bus_lane', models.BooleanField(default=False)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge')),
                ('map_versions', models.ManyToManyField(to='maps.mapversion')),
            ],
            options={
                'ordering': ('edge__game_map__name', 'edge__name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BusLineEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.busline')),
                ('street_edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.streetedge')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('bus_line', 'order')},
            },
        ),
        migrations.AddField(
            model_name='busline',
            name='edges',
            field=models.ManyToManyField(through='maps.BusLineEdge', to='maps.streetedge'),
        ),
        migrations.CreateModel(
            name='StreetPerRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_under_load', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.streetedge')),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='TrainEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge')),
                ('map_versions', models.ManyToManyField(to='maps.mapversion')),
            ],
            options={
                'ordering': ('edge__game_map__name', 'edge__name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('intervall', models.PositiveSmallIntegerField(default=5)),
                ('train_capacity', models.PositiveIntegerField()),
                ('train_speed_kmh', models.PositiveSmallIntegerField(default=40)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('map_versions', models.ManyToManyField(to='maps.mapversion')),
            ],
            options={
                'ordering': ('game_map', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TrainLineEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('train_edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.trainedge')),
                ('train_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.trainline')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('train_line', 'order')},
            },
        ),
        migrations.AddField(
            model_name='trainline',
            name='edges',
            field=models.ManyToManyField(through='maps.TrainLineEdge', to='maps.trainedge'),
        ),
    ]
