# Generated by Django 5.2.8 on 2025-12-12 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_dim', models.PositiveSmallIntegerField(default=10)),
                ('y_dim', models.PositiveSmallIntegerField(default=10)),
                ('scale', models.FloatField(default=1.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('node_type', models.ManyToManyField(to='maps.nodetype')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('bike_speed', models.PositiveSmallIntegerField(default=15)),
                ('walk_speed', models.PositiveSmallIntegerField(default=4)),
                ('max_lanes', models.PositiveSmallIntegerField(default=2)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='maps.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='maps.node')),
            ],
            options={
                'unique_together': {('start_node', 'end_node')},
            },
        ),
        migrations.CreateModel(
            name='StreetEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limit', models.PositiveSmallIntegerField(default=50)),
                ('lanes', models.PositiveSmallIntegerField(default=1)),
                ('dedicated_bus_lane', models.BooleanField(default=False)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge')),
            ],
        ),
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('frequency', models.FloatField()),
                ('bus_capacity', models.PositiveSmallIntegerField()),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
                ('edges', models.ManyToManyField(to='maps.streetedge')),
            ],
        ),
        migrations.CreateModel(
            name='TrainEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.edge')),
            ],
        ),
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('frequency', models.FloatField()),
                ('train_capacity', models.PositiveIntegerField()),
                ('edges', models.ManyToManyField(to='maps.trainedge')),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.gamemap')),
            ],
        ),
    ]
