# Generated by Django 5.2.8 on 2026-02-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='map_backgrounds/'),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_crop_bottom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_crop_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_crop_right',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_crop_top',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='image_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='mapversion',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='maps.mapversion'),
        ),
    ]
