# Generated by Django 5.2.8 on 2026-01-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapversion',
            options={'ordering': ('game_map', '-base_version', '-pk')},
        ),
        migrations.AddField(
            model_name='mapversion',
            name='base_version',
            field=models.BooleanField(default=False),
        ),
    ]
