# Generated by Django 5.2.8 on 2026-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversion',
            name='compatible_versions',
            field=models.ManyToManyField(to='maps.mapversion'),
        ),
    ]
