# Generated by Django 5.2.8 on 2026-01-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_mapversion_options_mapversion_base_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversion',
            name='poll_text',
            field=models.TextField(default='Die Karte soll ... '),
        ),
        migrations.AddField(
            model_name='mapversion',
            name='revert_poll_text',
            field=models.TextField(default='Die Karte soll ... '),
        ),
    ]
