# Generated by Django 5.2.8 on 2026-03-08 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_mapversion_compatible_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
