# Generated by Django 5.2.8 on 2026-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_mapversion_poll_text_mapversion_revert_poll_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
