# Generated by Django 5.2.8 on 2026-03-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_mapversion_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversion',
            name='change_img',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
