# Generated by Django 5.2.8 on 2026-01-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
