# Generated by Django 5.2.8 on 2026-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_mapversion_change_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busline',
            name='bus_capacity',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='trainline',
            name='train_capacity',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
