# Generated by Django 5.2.8 on 2026-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_edge_bike_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='co2_budget_kg_per_round',
            field=models.PositiveIntegerField(default=8000, help_text='Vorschlag für das CO₂-Budget, pro Runde in kg. Genug, wenn die Klasse umsteigt, zu wenig, wenn alle mit dem Auto fahren.'),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='district_commuters',
            field=models.PositiveIntegerField(default=6400, help_text='Pendler, die die Straßen dieser Karte im Berufsverkehr verkraften. Wird auf die Fahrgäste aufgeteilt, damit auf der Karte gleich viel Verkehr ist, egal wie viele mitspielen.'),
        ),
    ]
