# Generated by Django 5.2.8 on 2026-09-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_s17_wortwahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='calibrated',
            field=models.BooleanField(default=False, help_text='Ob Pendlerzahl und CO₂-Budget für diese Karte gemessen sind. Solange nicht, warnt das Formular „Spiel anlegen“, dass die Vorschläge nicht zur Karte passen müssen.'),
        ),
    ]
