# Generated by Django 5.2.8 on 2026-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_karte_kalibriert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='co2_budget_kg_per_round',
            field=models.PositiveIntegerField(default=16000, help_text='Vorschlag für das CO₂-Budget, pro Runde in kg. Genug, wenn viele umsteigen, zu wenig, wenn alle mit dem Auto fahren.'),
        ),
    ]
