# Generated by Django 5.2.8 on 2026-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_rundenbudget_hin_und_zurueck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemap',
            name='co2_budget_kg_per_round',
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='calibrated',
            field=models.BooleanField(default=False, help_text='Ob die Pendlerzahl für diese Karte gemessen ist. Solange nicht, warnt das Formular „Spiel anlegen“, dass die Menschen pro Gruppe nicht zur Karte passen müssen.'),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='district_commuters',
            field=models.PositiveIntegerField(default=6800, help_text='Pendler, die die Straßen dieser Karte im Berufsverkehr verkraften. Wird auf die Gruppen aufgeteilt, damit auf der Karte gleich viel Verkehr ist, egal wie viele mitspielen.'),
        ),
    ]
