# Generated by Django 5.2.8 on 2026-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_budget_pro_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetedge',
            name='tram_track',
            field=models.CharField(blank=True, choices=[('', 'keins in der Fahrbahn'), ('lane', 'Gleis in der Fahrspur'), ('own', 'eigenes Gleis')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='trainline',
            name='kind',
            field=models.CharField(choices=[('train', 'S- oder U-Bahn'), ('tram', 'Tram')], default='train', max_length=5),
        ),
    ]
